apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: workload.kcp.dev
spec:
  latestResourceSchemas:
  - v220926-3ab2a86d.synctargets.workload.kcp.dev
status: {}
